import type { Community, CommunityPost, PostReply } from "../types/community";

// ── Communities ──────────────────────────────────────────────────────

const communities: Community[] = [
  {
    id: "sf-moms",
    name: "SF Moms",
    description:
      "Connect with fellow moms in the San Francisco Bay Area. Share local tips, meetup ideas, and navigate city life with little ones.",
    coverPhotoURL: "https://picsum.photos/seed/sfmoms/600/400",
    category: "location",
    badge: "LOCATION",
    memberCount: 156,
    postCount: 42,
    lastActivityAt: new Date("2026-02-05T18:30:00"),
    tags: ["san francisco", "bay area", "local"],
    isPublic: true,
  },
  {
    id: "expecting-moms",
    name: "Expecting Moms",
    description:
      "A safe space for moms-to-be. Share your journey, ask questions about pregnancy, and find support from others who understand.",
    coverPhotoURL: "https://picsum.photos/seed/expecting/600/400",
    category: "child_age",
    badge: "AGE",
    memberCount: 145,
    postCount: 78,
    lastActivityAt: new Date("2026-02-06T09:15:00"),
    tags: ["pregnancy", "expecting", "prenatal"],
    isPublic: true,
  },
  {
    id: "sensitive-skin",
    name: "Sensitive Skin Society",
    description:
      "For parents navigating eczema, allergies, and sensitive skin issues. Product recs, routines, and emotional support.",
    coverPhotoURL: "https://picsum.photos/seed/skincare/600/400",
    category: "experience",
    badge: "EXPERIENCE",
    memberCount: 12,
    postCount: 19,
    lastActivityAt: new Date("2026-02-04T14:00:00"),
    tags: ["eczema", "allergies", "skincare"],
    isPublic: true,
  },
];

// ── Posts ─────────────────────────────────────────────────────────────

const posts: CommunityPost[] = [
  // ── SF Moms posts (5) ────────
  {
    id: "sf-post-1",
    communityId: "sf-moms",
    authorId: "u1",
    authorName: "Jamie L.",
    authorAvatar: "https://picsum.photos/seed/avatar1/100/100",
    body: "Does anyone know a good indoor play space in the Mission? It's been raining all week and my toddler is going stir-crazy 😅",
    timestamp: new Date("2026-02-05T16:22:00"),
    likeCount: 14,
    replyCount: 3,
    bookmarkCount: 2,
    pinned: false,
    notable: true,
  },
  {
    id: "sf-post-2",
    communityId: "sf-moms",
    authorId: "u2",
    authorName: "Priya S.",
    authorAvatar: "https://picsum.photos/seed/avatar2/100/100",
    body: "Just discovered the best coffee shop with a play corner in Noe Valley — Blue Bottle on 24th! The baristas are SO patient with kids.",
    timestamp: new Date("2026-02-05T11:05:00"),
    likeCount: 22,
    replyCount: 5,
    bookmarkCount: 8,
    pinned: false,
    notable: false,
  },
  {
    id: "sf-post-3",
    communityId: "sf-moms",
    authorId: "u3",
    authorName: "Maria G.",
    authorAvatar: "https://picsum.photos/seed/avatar3/100/100",
    body: "Anyone doing the Golden Gate Park stroller walk this Saturday? Would love to meet up!",
    timestamp: new Date("2026-02-04T09:30:00"),
    likeCount: 9,
    replyCount: 2,
    bookmarkCount: 1,
    pinned: false,
    notable: false,
  },
  {
    id: "sf-post-4",
    communityId: "sf-moms",
    authorId: "u4",
    authorName: "Sarah K.",
    authorAvatar: "https://picsum.photos/seed/avatar4/100/100",
    body: "PSA: The playground at Dolores Park has been renovated and it looks amazing! New swings and a little climbing wall for toddlers.",
    timestamp: new Date("2026-02-03T14:00:00"),
    likeCount: 31,
    replyCount: 4,
    bookmarkCount: 12,
    pinned: false,
    notable: false,
  },
  {
    id: "sf-post-5",
    communityId: "sf-moms",
    authorId: "u5",
    authorName: "Tina W.",
    authorAvatar: "https://picsum.photos/seed/avatar5/100/100",
    body: "Looking for pediatrician recommendations in the Sunset. We just moved and need someone who takes Blue Shield.",
    timestamp: new Date("2026-02-02T08:45:00"),
    likeCount: 6,
    replyCount: 3,
    bookmarkCount: 3,
    pinned: false,
    notable: false,
  },

  // ── Expecting Moms posts (5) ─
  {
    id: "exp-post-1",
    communityId: "expecting-moms",
    authorId: "u6",
    authorName: "Aisha R.",
    authorAvatar: "https://picsum.photos/seed/avatar6/100/100",
    body: "28 weeks today and the heartburn is NO JOKE. What's working for you ladies? I've tried everything 😭",
    timestamp: new Date("2026-02-06T07:00:00"),
    likeCount: 18,
    replyCount: 6,
    bookmarkCount: 4,
    pinned: false,
    notable: true,
  },
  {
    id: "exp-post-2",
    communityId: "expecting-moms",
    authorId: "u7",
    authorName: "Emily T.",
    authorAvatar: "https://picsum.photos/seed/avatar7/100/100",
    body: "Finally felt the first kick today at 19 weeks!! I cried happy tears in the middle of Target 🥹",
    timestamp: new Date("2026-02-05T20:30:00"),
    likeCount: 45,
    replyCount: 8,
    bookmarkCount: 2,
    pinned: false,
    notable: false,
  },
  {
    id: "exp-post-3",
    communityId: "expecting-moms",
    authorId: "u8",
    authorName: "Olivia M.",
    authorAvatar: "https://picsum.photos/seed/avatar8/100/100",
    body: "Hospital bag checklist — what am I forgetting? So far I have: robe, slippers, nursing bra, going-home outfit for baby, phone charger, snacks...",
    timestamp: new Date("2026-02-05T13:15:00"),
    likeCount: 27,
    replyCount: 12,
    bookmarkCount: 20,
    pinned: false,
    notable: false,
  },
  {
    id: "exp-post-4",
    communityId: "expecting-moms",
    authorId: "u9",
    authorName: "Noor A.",
    authorAvatar: "https://picsum.photos/seed/avatar9/100/100",
    body: "Second trimester energy is REAL. I deep-cleaned my entire apartment, organized the nursery, AND made dinner. Where was this energy in the first trimester?!",
    timestamp: new Date("2026-02-04T17:45:00"),
    likeCount: 38,
    replyCount: 5,
    bookmarkCount: 1,
    pinned: false,
    notable: false,
  },
  {
    id: "exp-post-5",
    communityId: "expecting-moms",
    authorId: "u10",
    authorName: "Rachel D.",
    authorAvatar: "https://picsum.photos/seed/avatar10/100/100",
    body: "TW: anxiety. Is anyone else terrified of labor? I know it'll be fine but I can't stop doom-scrolling birth stories. How do you manage the anxiety?",
    timestamp: new Date("2026-02-03T21:00:00"),
    likeCount: 33,
    replyCount: 9,
    bookmarkCount: 7,
    pinned: false,
    notable: false,
  },

  // ── Sensitive Skin Society posts (5) ─
  {
    id: "skin-post-1",
    communityId: "sensitive-skin",
    authorId: "u11",
    authorName: "Lily C.",
    authorAvatar: "https://picsum.photos/seed/avatar11/100/100",
    body: "We finally found a laundry detergent that doesn't trigger flare-ups — All Free & Clear. Game changer for us.",
    timestamp: new Date("2026-02-04T10:00:00"),
    likeCount: 11,
    replyCount: 4,
    bookmarkCount: 9,
    pinned: false,
    notable: true,
  },
  {
    id: "skin-post-2",
    communityId: "sensitive-skin",
    authorId: "u12",
    authorName: "Maya J.",
    authorAvatar: "https://picsum.photos/seed/avatar12/100/100",
    body: "Our allergist just confirmed egg and dairy allergies. Feeling overwhelmed about meal planning for a 14-month-old. Any tips?",
    timestamp: new Date("2026-02-03T16:30:00"),
    likeCount: 8,
    replyCount: 6,
    bookmarkCount: 5,
    pinned: false,
    notable: false,
  },
  {
    id: "skin-post-3",
    communityId: "sensitive-skin",
    authorId: "u13",
    authorName: "Dana P.",
    authorAvatar: "https://picsum.photos/seed/avatar13/100/100",
    body: "Eczema flare-up routine that actually works for us: lukewarm oatmeal bath → pat dry → Vanicream → wet wrap. Took months to figure out but it's been a lifesaver.",
    timestamp: new Date("2026-02-02T12:00:00"),
    likeCount: 19,
    replyCount: 7,
    bookmarkCount: 15,
    pinned: false,
    notable: false,
  },
  {
    id: "skin-post-4",
    communityId: "sensitive-skin",
    authorId: "u14",
    authorName: "Kim N.",
    authorAvatar: "https://picsum.photos/seed/avatar14/100/100",
    body: "Does anyone else feel guilty when strangers comment on their kid's skin? A woman at the park told me to 'just use lotion.' 😤",
    timestamp: new Date("2026-02-01T19:00:00"),
    likeCount: 25,
    replyCount: 8,
    bookmarkCount: 3,
    pinned: false,
    notable: false,
  },
  {
    id: "skin-post-5",
    communityId: "sensitive-skin",
    authorId: "u15",
    authorName: "Zara H.",
    authorAvatar: "https://picsum.photos/seed/avatar15/100/100",
    body: "Sunscreen recs for sensitive baby skin? We tried three different mineral ones and they all caused redness 😩",
    timestamp: new Date("2026-01-31T11:00:00"),
    likeCount: 7,
    replyCount: 5,
    bookmarkCount: 6,
    pinned: false,
    notable: false,
  },
];

// ── Replies ──────────────────────────────────────────────────────────

const replies: PostReply[] = [
  // sf-post-1 replies (3)
  {
    id: "r1",
    postId: "sf-post-1",
    authorId: "u2",
    authorName: "Priya S.",
    authorAvatar: "https://picsum.photos/seed/avatar2/100/100",
    body: "Peekadoodle on Valencia is amazing! They have drop-in hours too.",
    timestamp: new Date("2026-02-05T16:45:00"),
    likeCount: 5,
  },
  {
    id: "r2",
    postId: "sf-post-1",
    authorId: "u3",
    authorName: "Maria G.",
    authorAvatar: "https://picsum.photos/seed/avatar3/100/100",
    body: "The Randall Museum is free and has a great little play area for toddlers!",
    timestamp: new Date("2026-02-05T17:10:00"),
    likeCount: 3,
  },
  {
    id: "r3",
    postId: "sf-post-1",
    authorId: "u4",
    authorName: "Sarah K.",
    authorAvatar: "https://picsum.photos/seed/avatar4/100/100",
    body: "We love the Children's Creativity Museum on 4th St — great for rainy days!",
    timestamp: new Date("2026-02-05T18:00:00"),
    likeCount: 2,
  },

  // sf-post-2 replies (2)
  {
    id: "r4",
    postId: "sf-post-2",
    authorId: "u1",
    authorName: "Jamie L.",
    authorAvatar: "https://picsum.photos/seed/avatar1/100/100",
    body: "Omg adding this to my list! Does it get crowded on weekends?",
    timestamp: new Date("2026-02-05T11:30:00"),
    likeCount: 1,
  },
  {
    id: "r5",
    postId: "sf-post-2",
    authorId: "u5",
    authorName: "Tina W.",
    authorAvatar: "https://picsum.photos/seed/avatar5/100/100",
    body: "Yes!! We go there every Tuesday. The play corner saved my sanity.",
    timestamp: new Date("2026-02-05T12:00:00"),
    likeCount: 4,
  },

  // exp-post-1 replies (3)
  {
    id: "r6",
    postId: "exp-post-1",
    authorId: "u7",
    authorName: "Emily T.",
    authorAvatar: "https://picsum.photos/seed/avatar7/100/100",
    body: "Papaya enzyme tablets are a lifesaver! Completely natural and they work fast.",
    timestamp: new Date("2026-02-06T07:30:00"),
    likeCount: 8,
  },
  {
    id: "r7",
    postId: "exp-post-1",
    authorId: "u8",
    authorName: "Olivia M.",
    authorAvatar: "https://picsum.photos/seed/avatar8/100/100",
    body: "Sleeping propped up on two pillows helped me so much. Also avoiding eating 2 hours before bed.",
    timestamp: new Date("2026-02-06T08:00:00"),
    likeCount: 6,
  },
  {
    id: "r8",
    postId: "exp-post-1",
    authorId: "u9",
    authorName: "Noor A.",
    authorAvatar: "https://picsum.photos/seed/avatar9/100/100",
    body: "My OB prescribed famotidine and it was a game changer. Definitely ask yours!",
    timestamp: new Date("2026-02-06T08:30:00"),
    likeCount: 4,
  },

  // exp-post-2 replies (2)
  {
    id: "r9",
    postId: "exp-post-2",
    authorId: "u6",
    authorName: "Aisha R.",
    authorAvatar: "https://picsum.photos/seed/avatar6/100/100",
    body: "That's the BEST feeling! Congratulations mama! 💕",
    timestamp: new Date("2026-02-05T21:00:00"),
    likeCount: 12,
  },
  {
    id: "r10",
    postId: "exp-post-2",
    authorId: "u10",
    authorName: "Rachel D.",
    authorAvatar: "https://picsum.photos/seed/avatar10/100/100",
    body: "I remember that moment! It only gets more magical from here 🥰",
    timestamp: new Date("2026-02-05T21:30:00"),
    likeCount: 7,
  },

  // skin-post-1 replies (2)
  {
    id: "r11",
    postId: "skin-post-1",
    authorId: "u12",
    authorName: "Maya J.",
    authorAvatar: "https://picsum.photos/seed/avatar12/100/100",
    body: "We use the same one! Also recommend their dryer sheets — fragrance free too.",
    timestamp: new Date("2026-02-04T10:30:00"),
    likeCount: 3,
  },
  {
    id: "r12",
    postId: "skin-post-1",
    authorId: "u13",
    authorName: "Dana P.",
    authorAvatar: "https://picsum.photos/seed/avatar13/100/100",
    body: "Second this! We also do an extra rinse cycle to make sure all detergent is out.",
    timestamp: new Date("2026-02-04T11:00:00"),
    likeCount: 5,
  },

  // skin-post-2 replies (3)
  {
    id: "r13",
    postId: "skin-post-2",
    authorId: "u11",
    authorName: "Lily C.",
    authorAvatar: "https://picsum.photos/seed/avatar11/100/100",
    body: "It gets easier, I promise! We found so many great recipes on @solidstarts that are dairy & egg free.",
    timestamp: new Date("2026-02-03T17:00:00"),
    likeCount: 4,
  },
  {
    id: "r14",
    postId: "skin-post-2",
    authorId: "u14",
    authorName: "Kim N.",
    authorAvatar: "https://picsum.photos/seed/avatar14/100/100",
    body: "Oat milk yogurt was a great substitute for us. Also chickpea pasta is a hit!",
    timestamp: new Date("2026-02-03T17:30:00"),
    likeCount: 6,
  },
  {
    id: "r15",
    postId: "skin-post-2",
    authorId: "u15",
    authorName: "Zara H.",
    authorAvatar: "https://picsum.photos/seed/avatar15/100/100",
    body: "We see an allergist at UCSF and they've been incredible. Happy to share the name if you want!",
    timestamp: new Date("2026-02-03T18:00:00"),
    likeCount: 2,
  },
];

// ── Export functions ─────────────────────────────────────────────────

export function getMockCommunities(): Community[] {
  return communities;
}

export function getMockPosts(communityId?: string): CommunityPost[] {
  if (communityId) {
    return posts.filter((p) => p.communityId === communityId);
  }
  return posts;
}

export function getMockReplies(postId?: string): PostReply[] {
  if (postId) {
    return replies.filter((r) => r.postId === postId);
  }
  return replies;
}
